name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/php-idna-translator-release.yml@main
    secrets: inherit